### ISSUE TITLE
Some text not translated to English in tooltips

### ISSUE THREAD

**Issue by rnadams2** [greedyj4ck/DEGENESIS-FoundryVTT#100]
Hi! Thanks for such a fantastic system module! 

Playing around with it, I found a couple untranslated items (I'm assuming the original is German?) in the Cults tooltips -- both are the AGI skill bonuses listed. Nothing Google Translate couldn't overcome, though.

![bandicam 2023-10-14 14-37-59-615](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/40044921/c2061b63-ca54-405c-ad4e-cd6f0c789b32)
![bandicam 2023-10-14 14-37-18-734](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/40044921/35829a3a-4a68-4828-a27f-be640d1f2b8c)

**Comment by greedyj4ck** [comment]
Fixed :)
