### ISSUE TITLE
Acronyms for roll modifiers

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#104]
Hello

The roll modifiers are not shown accordingly in spanish. In the translated edition of Katharsys:
- S (success) is changed to E (éxito).
- T (trigger) > DT (desencadenante).
- C (challenge) > DS (desafiante).

F (force > fuerza) and D (dice > dados) are kept.

**Comment by greedyj4ck** [comment]
Thank you for feedback. 

Roll modifiers are and other acronyms are not translated to any language - they are hardcoded for now. I will handle this issue with next big release (Abberants sheets).

**Comment by greedyj4ck** [comment]
Fixed at the moment. This feature needs extensive testing.
