### ISSUE TITLE
Adding weapons

### ISSUE THREAD

**Issue by KristjanLaane** [greedyj4ck/DEGENESIS-FoundryVTT#11]
Fantastic work, so much better than the roll20 implementation. Is it possible to add melee, brawl and projectile weapons and then roll them? I could not find it, is it implemented? This is the only major thing missing as compared to roll20.

**Comment by moo-man** [comment]
The system is far from complete so yeah, probably, I thought I added that already but maybe not

**Comment by ClemEvilzz** [comment]
Hi ! Here is a quick video on how to do it ! 
Please note that sonic weapons don't work yet !
https://www.youtube.com/watch?v=pzzXOLEX0VQ

**Comment by KristjanLaane** [comment]
Amazing!!

**Comment by KristjanLaane** [comment]
There seems to be a bug with the force getting saved. If you watch your video closely, the F/3 value is cleared as soon as you do anythign else iwth another value. Same happens to me. So the damage is lower.

**Comment by ClemEvilzz** [comment]
Oh you are right, use raw value instead (calculate with the force manually), as Moo-man said if it isn't here it will be added in the future :)

**Comment by KristjanLaane** [comment]
I implemented the force aspects, made a pull request to the frontend branch..
