### ISSUE TITLE
Correct Sonic Weapons logic

### ISSUE THREAD

**Issue by greedyj4ck** [greedyj4ck/DEGENESIS-FoundryVTT#11]
Fix the logic behind sonic weapons attacks .

**Comment by MrMstislav** [comment]
Put in a PR https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/pull/12 but there is a small conflict with the roll card html handlebars on how the roll results are fetched. I'll update the logic for the mostSuccesses value to also be held as property of UI.

**Comment by MrMstislav** [comment]
Fixed in https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/pull/12 . Closed.
