### ISSUE TITLE
Reverse ego/wounds/trauma values

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#113]
Hey!

It seems the majority of modules and Foundry stuff that track ego/wounds/trauma are not compatible with systems like this, so been wondering if a 'reverse' version of these attributes could be created for tracking purposes, and be available in the resources list.

Thank you!

**Comment by greedyj4ck** [comment]
I will look into it, but with low priority.

**Comment by greedyj4ck** [comment]
I added three getters to actor entity: 

```js
get fleshwoundsReversed() {
    return (
      this.system.condition.fleshwounds.max -
      this.system.condition.fleshwounds.value
    );
  }

  get traumaReversed() {
    return (
      this.system.condition.trauma.max - this.system.condition.trauma.value
    );
  }

  get sporeReversed() {
    return this.system.condition.spore.max - this.system.condition.spore.value;
  }
  ```
  
  Please test it after V12 main release, and check if the 3rd party modules can work with getters, not with template values. 
  
  Note: implementing it at template level would be kind of pointless. If getters wont work, we will get back to the topic during migration to data models.
