### ISSUE TITLE
No defense roll available for NPC/FH

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#114]
Hello!
Looks like NPC/FH defense values are not rollable when clicking on them

Thank you!

**Comment by greedyj4ck** [comment]
Working fine on my side...
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/e7a52d1f-0f01-474c-ad1f-3062ce6f702b)
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/e0017475-76c6-438c-9c5d-d71e3c4289be)

![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/12980ef5-7ccf-4245-ad32-424af0ea7856)

Need more info.

**Comment by Dentatum** [comment]
Looks like "TYPE" parameter is not even showing up, and I think this is the clickable and rollable part :S
Tried both using '+' button and creating separately a defense item then moving it into the sheet.

![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/80d0f61a-55eb-4a8e-ae9b-a55e17284338)
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/bdfbc0d4-a7c6-4523-b1f4-5b1faee67288)

**Comment by greedyj4ck** [comment]
Can you share more details (os, foundry version, system version, used browser)?

**Comment by greedyj4ck** [comment]
Also @Dentatum can you check console for errors ?

**Comment by Dentatum** [comment]
Found out the issue is caused with a mod, Tokenmagic FX. Probably it's overriding anything. I'm uninstalling this, I think the issue is on the mod's end.

Just in case I'm mistaken about what's creating the conflict:
- Foundry v: 11.315
- System v: 0.6.1.2
- No apparent console errors except with mods that does not have available language packs
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/1fe5f6c9-c605-4ce0-97ed-7e0eeef84af7)

**Comment by greedyj4ck** [comment]
It is probably some CSS class conflict. Will look into that in a future, but closing for now.
