### ISSUE TITLE
Wrong distance in meelee Attack-type items

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#116]
Hello!

Sheets are showing always 1 in the range field on meelee attack-type items.
Both examples for FH and NPC sheets attached.
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/e3b3a144-fdd6-4230-a7f5-afb11abd277f)
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/1d3bdbdd-b1d8-4c56-a85c-d59b83aa96eb)

Thank you!

**Comment by greedyj4ck** [comment]
I left a placeholder there 🤣 Ty for catching this!
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/98e599bf-ed9c-4b79-9d97-b0298b16c383)
Gonna fix it in nearest release :D
