### ISSUE TITLE
Aberrant: Infestation and overload

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#124]
Scenario:
- Max temporary infestation points
- Max **permanent** infestation points
- Using phenomena with overload

Points are not substracted from the infestation pool, permanent points are limiting the temporary ones below.
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/d3e34331-3c11-452c-8978-f99d4786e104)

**Comment by greedyj4ck** [comment]
For now I locked ability to overload phenomenon if it would result in spore infestation points being lower than permanent ones. 

Afaik, Aberrants do not use permanent points mechanics - need to revise sheet design in a future.
