### ISSUE TITLE
DGNS.Number string missing

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#125]
Hello!
When trying to post a modifier into the chat, there's a string missing, associated with the number of the mod. I can't seem to find it in the lang files.
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/23096f24-a362-473a-b2df-8b9454896d8e)
Thank you!

**Comment by greedyj4ck** [comment]
"Number of the mod" is the number of rounds ?

**Comment by Dentatum** [comment]
It refers to the parameter "Number" inside the mod window, I believe
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/5ee2d0d9-6bfb-494e-8a31-c63918329ec6)

**Comment by greedyj4ck** [comment]
Ah, this modifier :)
