### ISSUE TITLE
Phenomena: Action number is using total infestation

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#126]
Hello!
I see phenomena rolls are taking total spore infestation instead of remaining ones
Tried using phenomena with 0 spore infestation left, rolled like 20
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/baaa3143-464b-479e-9c50-3afc038ca2e4)

**Comment by greedyj4ck** [comment]
Are you sure the state is primal? Action number passed is correct.

![Screenshot_2024-02-20-15-05-55-08_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/02f2bed0-952c-4954-91b7-56622b2a3090)

Will investigate.

**Comment by Dentatum** [comment]
This is happening in focus phase, my bad

**Comment by greedyj4ck** [comment]
In focus phase aberrant is using ego points. You can check if they are being removed on overload ;)

**Comment by Dentatum** [comment]
When I try to overload in focus phase it's still trying to get from current infestation instead of ego, so in a situation of 0 spore left, overload is not possible in focus phase. Not sure if this is what you mean

**Comment by greedyj4ck** [comment]
Nvm, I thought that in focus phase aberrant could use ego points to overload phenomenon, but i guess its not a case.  Closing the issue for now :) 
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/b608d8aa-64d4-4a9f-9aea-7c5a5cf16ee1)
