### ISSUE TITLE
No Dice still roll 1 Dice

### ISSUE THREAD

**Issue by Calion16** [greedyj4ck/DEGENESIS-FoundryVTT#130]
Hi!
If the actor doesn't have any dice for an attack (due to malus, for example) or doesn't have any Spore/Ego to activate a Phenomenon, they can still attempt the roll with one die. If no die can be rolled, the action should not be able to proceed.
Thanks :)

**Comment by greedyj4ck** [comment]
Its a settable option.

![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/f2f0edd5-5989-4a95-b76e-2ecccdc9853d)

**Comment by Calion16** [comment]
Oh! Thank you so much. 
I didn't know that. 
Sorry! My bad!
