### ISSUE TITLE
Roll settings: Modifiers not applied when pressing ENTER

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#137]
Not sure if this is more like a feature request, but modifiers only work when clicking on "Roll" button after setting them up.
Could this also be programmed to be applied when ENTER is pressed?

Im talking about this menu. Currently, when hitting enter, it rolls without modifiers:
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/51b0c3d8-1d38-482e-b823-0f5c0e46cdc4)

**Comment by greedyj4ck** [comment]
Does pressing Enter triggers roll without modifiers or does nothing at all ? 

I think I can add keyOn event listener to confirm roll.

**Comment by Dentatum** [comment]
It rolls without modifiers, editing op

**Comment by greedyj4ck** [comment]
Will look into that.

**Comment by greedyj4ck** [comment]
@Dentatum 
Roll parameters are getting updated on input value change event, which is triggered after input element loose focus. Its a simply fix. For now you can add this one liner to roll-dialog.js 

![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/33233389/5fb81bd9-19e7-4fc4-82e2-4d81bc72ca95)

Fix will be implemented in next major release ;)
