### ISSUE TITLE
Legacy prerequisite bug

### ISSUE THREAD

**Issue by Ragswolf** [greedyj4ck/DEGENESIS-FoundryVTT#14]
A very weird bug involving legacy items where the prerequisite paragraph copies its contents recurringly every time you click on the space where the 2 prerequisite writing spaces are, as well as the bonus, legacy, and drawback paragraphs. As you can see in the picture.

![weird bug](https://user-images.githubusercontent.com/5589661/100526289-7489ad00-3195-11eb-99b3-a21193f08bcb.PNG)

**Comment by moo-man** [comment]
Please be careful here, as this probably duplicates data upon updates, and your db files can grow very large, very quickly

**Comment by alexpouteau** [comment]
I pushed the dev-frontend in master, it should be fixed now. You just need to re download the master

**Comment by Ragswolf** [comment]
The fix worked. Thanks, Alex! 
Although, I just realized legacy items don't actually attach to the actor sheet yet.
