### ISSUE TITLE
Old School potential: Increase Trauma to 15

### ISSUE THREAD

**Issue by Dentatum** [greedyj4ck/DEGENESIS-FoundryVTT#140]
Hello!

According to 'Old School' potential, Trauma may increase over its max limit (12). This can make up to 15 points (CUE+PSI or PSIx2 +3 at level 3 potential)
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/bd527e32-9c1b-42a9-8aff-9c215e2db72d)

However, when trauma is override to reflect this, text shows as 15, but diamonds stay in 12, so no more than 12 points can be received.
![image](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/fb53152f-9cab-4275-98d9-def87995edfa)

May Trauma diamonds be increased in order to allow this?
Thank you!

**Comment by greedyj4ck** [comment]
This is something I want to tackle since like forever. I will figure something out as a quick fix for V12, but want to redesign entire potentials/legacies so they will be mechanized properly.
