### ISSUE TITLE
Chatlog not displaying in Foundry

### ISSUE THREAD

**Issue by magee101** [greedyj4ck/DEGENESIS-FoundryVTT#176]
I am on version 11.315 Foundry; Degenesis 0.7.6, my chatlog no longer displays inside Foundry itself. I was able to export a chatlog and it IS recording the chat; but there's no display for anyone not even me the DM
[fvtt-log-Sun-Aug-18-2024.txt](https://github.com/user-attachments/files/16653227/fvtt-log-Sun-Aug-18-2024.txt)
![image](https://github.com/user-attachments/assets/2ce9a88a-7395-40d2-9834-a9c80ca80efb)

I turned off all my modules to double check it wasn't something wrong there and even with all modules turned off the chatlog is not displaying. If there's any other information I can send you for this issue please let me know

**Comment by greedyj4ck** [comment]
0..7.X is not compatible with Foundry v11. Update to V12 and see if the issue persists.

**Comment by magee101** [comment]
Once I reverted back to 6.XX the chat began to function again, purely a weird interaction of backups and wrong versioning thanks for the quick response! <3
