### ISSUE TITLE
Items to chat / loot functionality?

### ISSUE THREAD

**Issue by PiotrZakrzewski** [greedyj4ck/DEGENESIS-FoundryVTT#26]
Hi! I was wondering if it was possible to send items to chat so that users can add them to their characters if they want to or maybe add them to loot on the map.
I could also implement it myself if you could point me to where to start.

PS: Thanks for making this module! Much appreciated!

**Comment by moo-man** [comment]
It's on my list certainly, as the buttons to post chat are there. 

Feel free to try it, but note I'm starting work towards FVTT 0.8 Compatibility, which changes a lot of things, so it could have a lot of conflicts

**Comment by PiotrZakrzewski** [comment]
For now I create a table I call loot and then add items to it. Rolling items on it posts them to the chat and allows players to drag and drop them.
