### ISSUE TITLE
Spending ego

### ISSUE THREAD

**Issue by PiotrZakrzewski** [greedyj4ck/DEGENESIS-FoundryVTT#32]
I am trying to figure out how spending ego was supposed to work, but there is at least one bug in there (See screenshot of the console). It happens on well, setting a value in `spend ego` and rolling for initiative.
<img width="519" alt="degenesis_ego_bug" src="https://user-images.githubusercontent.com/1050269/119886392-321e0e80-bf33-11eb-8f49-58e84951e7f4.png">
If you give me some hints I can fix it!

**Comment by moo-man** [comment]
I can't seem to reproduce this. Are you on the most recent degenesis and foundry versions?

**Comment by PiotrZakrzewski** [comment]
it was on beta. I will try again this weekend.

**Comment by PiotrZakrzewski** [comment]
Can't reproduce on the newest version
