### ISSUE TITLE
(Tiny bug) Custom modifiers don't expand on click

### ISSUE THREAD

**Issue by Mjb141** [greedyj4ck/DEGENESIS-FoundryVTT#35]
https://github.com/moo-man/DEGENESIS-FoundryVTT/blob/ca9392e98067bdd3a9eca5ca02e2eb7c35755e65/module/item/item-degenesis.js#L206

`this.data.this.description` -> `this.data.data.description`

**Comment by greedyj4ck** [comment]
Should be fixed already, but if not, open it again :)
