### ISSUE TITLE
Putting any Shield in inventory "locks" the entire sheet.

### ISSUE THREAD

**Issue by kurosaru69** [greedyj4ck/DEGENESIS-FoundryVTT#37]
When a character has a shield in their inventory the entire sheet is "locked." Seems like foundry reads all value as Null when attempting to roll!

**Comment by greedyj4ck** [comment]
Cannot reproduce the issue - can you share more details ?

**Comment by greedyj4ck** [comment]
> When a character has a shield in their inventory the entire sheet is "locked." Seems like foundry reads all value as Null when attempting to roll!

nvm, found the issue
![image](https://user-images.githubusercontent.com/33233389/121407102-3f89be80-c95f-11eb-84d2-2ef6d473db8b.png)
