### ISSUE TITLE
Vocoder minor bug

### ISSUE THREAD

**Issue by Ikabodo** [greedyj4ck/DEGENESIS-FoundryVTT#39]
As far as I know Vocoder is an exception to the normal Combination roll.
> Enemies defend with PSY+Faith/Willpower against the Difficulty set **by the higher of the two rolls**. If they lose, they take the Damage stated.

**Comment by greedyj4ck** [comment]
@MrMstislav can we close this one? Was it fixed in sonic weapons patch?

**Comment by MrMstislav** [comment]
Yep, it's patched
