### ISSUE TITLE
[Bug] Special Quality doesn't allow any input

### ISSUE THREAD

**Issue by undesconocido** [greedyj4ck/DEGENESIS-FoundryVTT#41]
![image](https://user-images.githubusercontent.com/11449491/126037545-1cfa1c49-d93f-49fd-8cce-bf1b125a1d36.png)

Quality Special in theory bring out a new text area, Specialty on the picture, where you could specify why this is special, any input is delete as soon as you lost focus on the text box.

**Comment by greedyj4ck** [comment]
Fixed :)

**Comment by greedyj4ck** [comment]
Close issue please :)
