### ISSUE TITLE
[Bug] Combat modifiers are not been updated properly

### ISSUE THREAD

**Issue by undesconocido** [greedyj4ck/DEGENESIS-FoundryVTT#42]
A lot of Combat values are wonky at best or broken right now

![image](https://user-images.githubusercontent.com/11449491/126037783-7095bd34-5daf-444d-a15b-8c4884835750.png)

On this NPC Encumbrance should be 7/8, the Combat screen is not picking that up even thou the Inventory screen is 
![image](https://user-images.githubusercontent.com/11449491/126037897-65af0910-3b69-49d3-887c-bce9772e3aba.png)

Armour should be 3 (1 by Item, 2 by Modifiers) if the Modifier is ON, but even with the Modifier to off, the value is still added.
![image](https://user-images.githubusercontent.com/11449491/126037947-01544a3a-4641-44fb-a36b-06318ebe00ed.png)
![image](https://user-images.githubusercontent.com/11449491/126037952-1d67c7b3-2786-4291-a26e-daf8d345fa8c.png)

Movement modifiers aren't added
Passive defense modifiers don''t work
Active defense doesn't popup anywhere too

**Comment by greedyj4ck** [comment]
Fixed armor and passive defence modifiers. Need to look into movement.

Encumbrance values are displayed properly now.

Active defense rolls are displayed per weapon equipped :)

**Comment by greedyj4ck** [comment]
Was this solved already? If yes please close the issue :)

**Comment by undesconocido** [comment]
I stopped playing Degenesis after finishing BA :P, If you say the issue is addressed I trust you. If I came back to the system and notice anything I'll let you know.
