### ISSUE TITLE
(Bug) Foundry VTT Version 9 Build 238

### ISSUE THREAD

**Issue by pplurueda** [greedyj4ck/DEGENESIS-FoundryVTT#47]
No sheet seems to open correctly.

This is a actor sheet
![Captura de pantalla 2021-12-23 174600](https://user-images.githubusercontent.com/82481289/147269702-795319fb-8b2f-4034-b415-b047277c32b6.png)

This is a weapon sheet
![Captura de pantalla 2021-12-23 174628](https://user-images.githubusercontent.com/82481289/147269713-cccb6bf6-09b1-42cd-a94f-d983e59e24f7.png)
.

**Comment by greedyj4ck** [comment]
Fix is already waiting for acceptance.
