### ISSUE TITLE
Roll dialogue and chat roll card need localization

### ISSUE THREAD

**Issue by TheHerugrim** [greedyj4ck/DEGENESIS-FoundryVTT#55]
roll dialogue
https://github.com/moo-man/DEGENESIS-FoundryVTT/blob/e2989d96173322254fee9ad5d9daf609f6025d03/templates/apps/roll-dialog.html#L8
and the rest of the lines that i didnt mark

roll card
https://github.com/moo-man/DEGENESIS-FoundryVTT/blob/e2989d96173322254fee9ad5d9daf609f6025d03/templates/chat/roll-card.html#L14-L17

**Comment by greedyj4ck** [comment]
We gonna rework that a bit for 0.5.0 or later release and include translation strings.
