### ISSUE TITLE
[Bug] Shield attack modifier showing as [object Object] when sent to chat

### ISSUE THREAD

**Issue by TheHerugrim** [greedyj4ck/DEGENESIS-FoundryVTT#58]
![grafik](https://user-images.githubusercontent.com/110698994/183249698-917577c7-a029-49c9-bf1b-a1af66812334.png)
When sending a shield to chat, the attack modifier shows up as [object Object]
Otherwise, the modifier seems to be added correctly when attacking with a weapon

**Comment by greedyj4ck** [comment]
Fixed.
