### ISSUE TITLE
Mods tab in any weapon and armor is non-functional

### ISSUE THREAD

**Issue by SIRIUS05627** [greedyj4ck/DEGENESIS-FoundryVTT#59]
Maybe it'll be worked on later, just wanted to inform about it
![image](https://user-images.githubusercontent.com/48809718/183887332-8bb599ff-496c-4206-8aa0-e0086a9cff00.png)

**Comment by greedyj4ck** [comment]
They are working. You need to create modification item and drag n drop it on character sheet. For now you cannot edit them directly on character sheet (probably due to way they are implemented atm). Gonna try to revise them later :)

**Comment by greedyj4ck** [comment]
Closing the issue for now.
