### ISSUE TITLE
Impossible to install the system

### ISSUE THREAD

**Issue by Mandraw** [greedyj4ck/DEGENESIS-FoundryVTT#62]
![image](https://user-images.githubusercontent.com/7592056/188222725-7fb4c5a9-61ff-4002-8e8f-1afec1981e98.png)
`[degenesis] Metadata validation failed for system "degenesis": The file "systems/degenesis/node_modules/dist/tippy.cjs" included by system degenesis does not exist`

Completely blocks the installation.
I am on Version 10 - Build 284 and the server is hosted on molten.

To reproduce:
1) Try installing Degenesys from the Game Systems tabs
2) Cry

**Comment by greedyj4ck** [comment]
Moo-man discontinued development of the system.  You can find up to date fork here: https://github.com/greedyj4ck/DEGENESIS-FoundryVTT

**Comment by Mandraw** [comment]
> Moo-man discontinued development of the system. You can find up to date fork here: https://github.com/greedyj4ck/DEGENESIS-FoundryVTT

Oh, okay thanks ! and thanks for continuing the development ! Then do I just update the manifest with yours ?

Edit : I did and it worked like a charm, Nice !
