### ISSUE TITLE
Mod not reflected in combat values

### ISSUE THREAD

**Issue by mhiner** [greedyj4ck/DEGENESIS-FoundryVTT#65]
I created a modification item for handling and set it with the key handling => add => 1

I then added the item to a weapon.  In the inventory section of the actor the description shows the added handling correctly, along with the other attributes.  If I add the handling mod a second time it increments the value a second time.

Under combat however the value for attack dice only includes the handling value for the base weapon.

**Comment by greedyj4ck** [comment]
Newest version or v9?

**Comment by mhiner** [comment]
newest version.  The install of both Foundry and add-on are less than 36 hours old.   (Working my way through testing things and learning the platform)

I took a marvel, added 1 to handling by quality (to make sure that it recognized the attribute) and 2 handling mods (to make sure it was not ignoring only the first mod)  giving a handling of +3D

![Marvel Display](https://user-images.githubusercontent.com/1047430/193457595-d23cc9cb-0279-45c4-a93d-958f6f38b5cc.png)

The mod itself

![handling_mod](https://user-images.githubusercontent.com/1047430/193457606-fd399fdc-b60e-4c08-8f30-457487ebc165.png)

The test char has a base 6 for projectlies

![attibutes](https://user-images.githubusercontent.com/1047430/193457618-71527a2f-b342-4d7f-b114-00039d896aba.png)

but the combat tab only lists 7D

![combat](https://user-images.githubusercontent.com/1047430/193457648-4a0de2ae-7e58-4dbe-b159-0de4b5f2325e.png)

Version info

![version](https://user-images.githubusercontent.com/1047430/193457655-8112dc51-19a8-4e8c-a843-b60614ebddf3.png)

**Comment by greedyj4ck** [comment]
Thanks, will check it out.

**Comment by greedyj4ck** [comment]
Found the culprit - apply mods function is firing after preparing data for weapons (calculating AN).

**Comment by greedyj4ck** [comment]
Changed order of executing functions, seems to be working properly now. Fix will appear with the release of 0.5.1
