### ISSUE TITLE
Ammo load in magazine starts at 0 and cannot be loaded

### ISSUE THREAD

**Issue by mhiner** [greedyj4ck/DEGENESIS-FoundryVTT#66]
When a ranged weapon is assigned to an actor with appropriate ammunition in their inventory the weapon reads "0/<capacity"  e.g. "0/5".  When an attack is made the first number is decremented leading to negative values.  e.g. "-1/5"

**Comment by mhiner** [comment]
I am not certain but I believe it may be that the "C" in "caliber" on this line should be lower case.

https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/blob/24d58f082f204537d0e76cb5df5b482a7cf9fb4a/module/item/item-degenesis.js#L171

**Comment by greedyj4ck** [comment]
Will investigate :)

**Comment by greedyj4ck** [comment]
Thinking about solving this one - I can create conditional preventing users from attacking with range weapon without any ammunition in magazine.

**Comment by mhiner** [comment]
I am not sure if that will solve it alone.  I may have been doing something wrong but I could not get the gun to load ammunition from inventory.  I tried 5.56 and lead bullet both on a marvel, in the case of the 5.56 I modified the weapon directly rather than using a modification.

It would help with the negative numbers but not the fact that I could not get it to be positive either.  (I grant this may be user error)

**Comment by greedyj4ck** [comment]
Maybe there is something wrong with the items itself. Will check it out.  Working fine on my side (at least partially)
![reload](https://user-images.githubusercontent.com/33233389/193679972-394da096-58f0-4c1b-85ed-bb6b610a21f4.gif)

**Comment by greedyj4ck** [comment]
Just tested Marvel with Lead Bullets, working fine. What version are you on?

**Comment by mhiner** [comment]
Disregard, it must have been operator error.  I just tried again and it works.

**Comment by greedyj4ck** [comment]
Np. Still will add a soft lock preventing user attacking without ammo (toggleable from options). Closing issue for now :)

**Comment by Dentatum** [comment]
Sorry for necromancy, but I'm having this same error as well
![imagen](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/3a0a6080-c075-47b5-b134-4f1ff1e2da07)

**Comment by greedyj4ck** [comment]
> Sorry for necromancy, but I'm having this same error as well
> ![imagen](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/3a0a6080-c075-47b5-b134-4f1ff1e2da07)
> 

Sorry to hear that. I need more information like the system version and steps to reproduce the issue. I never managed to reproduce it on my side.

**Comment by Dentatum** [comment]
Sure!
Foundry 11.315 - Degenesis 0.6.1.2

[www_screencapture_com_2023-11-15_19_48.webm](https://github.com/greedyj4ck/DEGENESIS-FoundryVTT/assets/148975371/30e51391-9423-4e19-ba6e-a36942d05d07)
The system automatically substracts 1 ammo from the magazine when clicking the distance to roll the attack, no matter the current one in the magazine.

Happens with any distance option on shooting.

**Comment by greedyj4ck** [comment]
Thanks, I will look into the bug and release a fix with a next milestone.

**Comment by greedyj4ck** [comment]
Fixed.

Release planned for 0.6.2.
