### ISSUE TITLE
Vocoder Defend against calculated incorrectly

### ISSUE THREAD

**Issue by kurosaru69** [greedyj4ck/DEGENESIS-FoundryVTT#75]
When performing a vocoder attack the "Defend Against" value seems to be the success from both rolls combined when it should only be the highest of the two rolls.
Page 166 of KatharSys: "Enemies defend with PSY+Faith/Willpower against the Difficulty set by the higher of the two rolls."

**Comment by MrMstislav** [comment]
![image](https://user-images.githubusercontent.com/14331607/198224327-d8a71794-29e7-4037-a4f8-067778192798.png)

working fine on my side, can you elaborate on the deets?

**Comment by kurosaru69** [comment]
Huh... it seems like it has something to do with a modifier my player is using for child of the stream! Gonna test some more.

**Comment by MrMstislav** [comment]
Modifiers are fiddly AF, let me know if you come up with something, I´ll run some test myself.

**Comment by greedyj4ck** [comment]
@kurosaru69 any feedback for this issue?
