### ISSUE TITLE
NPC character sheets?

### ISSUE THREAD

**Issue by CarWashMeNot** [greedyj4ck/DEGENESIS-FoundryVTT#82]
I am new to degenesis foundry-version, but how do the NPCs work? When i create an NPC-Actor I am not able to open any charactersheet when clicking on his name.

Also, is there a discord for this? Don't want to bother you opening issues for every question I am having :D

**Comment by greedyj4ck** [comment]
Hi,
NPC characters are not implemented yet - its a remnant of the past. You need to use actor sheets for now :) 

You can find link to discord server here :) https://discord.gg/JWUBSYqz
